title:          "Unofficial GitHub Buttons"
description:    "A set of static buttons with dynamic watch and fork counts for any repo hosted on GitHub."
url:            "https://ghbtns.com"

# Social
author:
  name:         "Mark Otto"

twitter:
  username:     "mdo"

permalink:      pretty

sass:
  style:        compressed

source:         docs

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
